version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/**'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: 'pip'
    directories:
      - '/**'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: "linkml"
        versions: [ "1.11.x" ]

  - package-ecosystem: 'gradle'
    directory: '/code-generators/java-types'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    groups:
      junit-dependencies:
        patterns:
          - org.junit.jupiter*
          - org.junit*
    ignore:
      - dependency-name: "gradle-wrapper"
        versions: [ "9.x" ]
      - dependency-name: "org.jsonschema2pojo"
        versions: [ "1.3.x" ]
      - dependency-name: "org.jsonschema2pojo:jsonschema2pojo-core"
        versions: [ "1.3.x" ]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    pull-request-branch-name:
      separator: '-'
