services:
  docs:
    build:
      context: .
    ports:
      - 8000:8000
    command: "/app/scripts/generate_json_schemas.sh -j /app/code-generators/typescript-types/schemas -o combined"
    volumes:
      - ./v1/linkml-schemas:/app/v1/linkml-schemas
      - ./code-generators/java-types/schemas:/app/code-generators/java-types/schemas
      - ./code-generators/typescript-types/schemas:/app/code-generators/typescript-types/schemas
