#!/usr/bin/env bash
ROOT_DIR="$( git rev-parse --show-toplevel )"
set -e

EXAMPLES=(
  "PostalAddressClass"
  "PassportDetailsClass"
  "DrivingPermitDetailsClass"
  "ResidencePermitDetailsClass"
  "SocialSecurityRecordDetailsClass"
  "IdCardDetailsClass"
  "NameClass"
)

bash "${ROOT_DIR}/scripts/generate_json_schemas.sh"

rm -rf "${ROOT_DIR}/docs/v1"
poetry run gen-markdown "${ROOT_DIR}/v1/linkml-schemas/credentials.yaml" -d "${ROOT_DIR}/docs/v1/" --index-file index.md
ln -s "${ROOT_DIR}/v1/linkml-schemas" "${ROOT_DIR}/docs/v1/linkml-schemas"
ln -s "${ROOT_DIR}/v1/json-schemas" "${ROOT_DIR}/docs/v1/json-schemas"

echo "Building examples"
mkdir "${ROOT_DIR}/docs/v1/examples"
for EXAMPLE in "${EXAMPLES[@]}"; do
  cp -R "${ROOT_DIR}/v1/examples/${EXAMPLE}" "${ROOT_DIR}/docs/v1/examples/${EXAMPLE}"
done


echo "Building Nav Bar"
python3 "${ROOT_DIR}/scripts/build_nav.py"

poetry run mkdocs build -c
