#!/bin/bash
HERE=`dirname "$0"`
set -e

rm -f $HERE/../v1/json-schemas/*.json
poetry run gen-json-schema --closed --no-metadata -t CoreIdentityJWTClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/CoreIdentityJWT.json
poetry run gen-json-schema --closed --no-metadata -t IdentityCheckCredentialJWTClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json
poetry run gen-json-schema --closed --no-metadata -t IdentityCheckCredentialClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/IdentityCheckCredential.json

rm -rf $HERE/../docs/v1
poetry run gen-markdown $HERE/../v1/linkml-schemas/credentials.yaml -d $HERE/../docs/v1/ --index-file index.md
ln -s ../../v1/linkml-schemas $HERE/../docs/v1/linkml-schemas
ln -s ../../v1/json-schemas $HERE/../docs/v1/json-schemas

poetry run mkdocs build -c
