#!/bin/bash
HERE=`dirname "$0"`
set -e

rm -f $HERE/../v1/json-schemas/*.json
poetry run gen-json-schema --closed --no-metadata -t CoreIdentityJWTClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/CoreIdentityJWT.json
poetry run gen-json-schema --closed --no-metadata -t IdentityCheckCredentialJWTClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json
poetry run gen-json-schema --closed --no-metadata -t IdentityCheckCredentialClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/IdentityCheckCredential.json
poetry run gen-json-schema --closed --no-metadata -t IssuerAuthorizationRequestClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/IssuerAuthorizationRequest.json
poetry run gen-json-schema --closed --no-metadata -t OpenIDConnectAuthenticationRequestClass $HERE/../v1/linkml-schemas/credentials.yaml > $HERE/../v1/json-schemas/OpenIDConnectAuthenticationRequest.json
poetry run gen-json-schema --closed --no-metadata -t PostalAddressClass $HERE/../v1/linkml-schemas/address.yaml > $HERE/../v1/json-schemas/PostalAddress.json
poetry run gen-json-schema --closed --no-metadata -t PassportDetailsClass $HERE/../v1/linkml-schemas/document.yaml > $HERE/../v1/json-schemas/PassportDetails.json
poetry run gen-json-schema --closed --no-metadata -t DrivingPermitDetailsClass $HERE/../v1/linkml-schemas/document.yaml > $HERE/../v1/json-schemas/DrivingPermit.json
poetry run gen-json-schema --closed --no-metadata -t ResidencePermitDetailsClass $HERE/../v1/linkml-schemas/document.yaml > $HERE/../v1/json-schemas/ResidencePermit.json
poetry run gen-json-schema --closed --no-metadata -t NameClass $HERE/../v1/linkml-schemas/name.yaml > $HERE/../v1/json-schemas/Name.json

rm -rf $HERE/../docs/v1
poetry run gen-markdown $HERE/../v1/linkml-schemas/credentials.yaml -d $HERE/../docs/v1/ --index-file index.md
mkdir $HERE/../docs/v1/examples
ln -s ../../v1/linkml-schemas $HERE/../docs/v1/linkml-schemas
ln -s ../../v1/json-schemas $HERE/../docs/v1/json-schemas
cp -R $HERE/../v1/examples/PostalAddressClass $HERE/../docs/v1/examples/PostalAddressClass
cp -R $HERE/../v1/examples/PassportDetailsClass $HERE/../docs/v1/examples/PassportDetailsClass
cp -R $HERE/../v1/examples/DrivingPermitDetailsClass $HERE/../docs/v1/examples/DrivingPermitDetailsClass
cp -R $HERE/../v1/examples/ResidencePermitDetailsClass $HERE/../docs/v1/examples/ResidencePermitDetailsClass
cp -R $HERE/../v1/examples/NameClass $HERE/../docs/v1/examples/NameClass

sass --quiet-deps --load-path $HERE/../node_modules/tech-docs-assets/stylesheets --load-path $HERE/../node_modules/govuk-frontend $HERE/../mkdocs-govuk/src/css/:$HERE/../docs/css
npx webpack build --config $HERE/../webpack.config.js
mkdir -p $HERE/../docs/assets/govuk/assets
cp -R $HERE/../node_modules/govuk-frontend/govuk/assets/* $HERE/../docs/assets/govuk/assets

poetry run mkdocs build -c
