#!/bin/bash
HERE=`dirname "$0"`
set -e

ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/CoreIdentityJWT.json -d $HERE/../v1/examples/identity-jwt.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredential.json -d $HERE/../v1/examples/doc-validity-valid.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json -d $HERE/../v1/examples/app-gdc-liveness-likeness-jwt.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json -d $HERE/../v1/examples/identity-check-jwt.json

