#!/bin/bash
HERE=`dirname "$0"`
set -e

ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/CoreIdentityJWT.json -d $HERE/../v1/examples/identity-jwt.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredential.json -d $HERE/../v1/examples/doc-validity-valid.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredential.json -d $HERE/../v1/examples/driving-permit.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json -d $HERE/../v1/examples/app-gdc-liveness-likeness-jwt.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IdentityCheckCredentialJWT.json -d $HERE/../v1/examples/identity-check-jwt.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/IssuerAuthorizationRequest.json -d $HERE/../v1/examples/core-cri-authz-request.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/OpenIDConnectAuthenticationRequest.json -d $HERE/../v1/examples/rp-authz-request.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/DeathRegistrationJWT.json -d $HERE/../v1/examples/life-events/death-registration.json
ajv validate -c ajv-formats -s $HERE/../v1/json-schemas/DeathRegistrationUpdateJWT.json -d $HERE/../v1/examples/life-events/death-registration-update.json
