name: 'Build, test, deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - name: Install Global JS dependencies
        run: npm install -g ajv-cli@5.0.0 ajv-formats@2.1.1

      - name: Install JS
        run: npm ci

      - name: Install Python
        run: poetry install

      - name: Build
        run: scripts/build

      # Creates file "$/files.json", among others
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'

      # For verification
      - name: Show files changed
        run: cat $HOME/files.json

      - name: Run all tests
        run: scripts/test

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v1.0.6
        with:
          path: site


