name: Deploy site and create release

on:
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab (but only on the default branch :shrug:)
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# and creation of releases.
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job imported
  build:
    uses: ./.github/workflows/build-test.yml

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v1.0.6
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Download JSON Schemas
        uses: actions/download-artifact@v3
        with:
          name: json-schemas
          path: v1/json-schemas

      # Ideally, we'd use the git tag as the release name
      - name: Calculate release name
        id: release-name
        run: |
          FULL_SHA="${{ github.sha }}"
          echo "short_sha=${FULL_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Release JSON Schemas
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
        with:
          files: |
            v1/json-schemas/*
          tag_name: ${{ steps.release-name.outputs.short_sha }}
          draft: false
          prerelease: false
